{"version":3,"file":"errorHandler.mjs","sources":["../../../packages/utils/errorHandler.ts"],"sourcesContent":["import { nextTick } from \"vue\";\nimport { consoleError, consoleWarn } from \"@fast-element-plus/utils\";\nimport { AxiosError } from \"axios\";\nimport { ElNotification } from \"element-plus\";\n\n/**\n * 全局异常捕获\n */\nexport const errorHandler = (error: any): boolean => {\n\tif (!error) return;\n\t// 过滤 Axios 错误\n\tif (error instanceof AxiosError) {\n\t\treturn false;\n\t}\n\tconst errorMap: any = {\n\t\tInternalError: \"Javascript引擎内部错误\",\n\t\tReferenceError: \"未找到对象\",\n\t\tTypeError: \"使用了错误的类型或对象\",\n\t\tRangeError: \"使用内置对象时，参数超范围\",\n\t\tSyntaxError: \"语法错误\",\n\t\tEvalError: \"错误的使用了Eval\",\n\t\tURIError: \"URI错误\",\n\t\tAggregateError: \"未知的多个错误\",\n\t\tTimeoutError: \"操作超时\",\n\t\tNetworkError: \"网络错误\",\n\t\tOutOfMemoryError: \"内存溢出\",\n\t};\n\tif (error === \"cancel\") {\n\t\tconsoleWarn(\"Cancel\", \"操作已取消\");\n\t} else {\n\t\tconst errorName = errorMap[error.name] || \"未知错误\";\n\t\tconsoleError(\"Handler\", error);\n\t\tnextTick(() => {\n\t\t\tElNotification({\n\t\t\t\ttitle: \"系统错误\",\n\t\t\t\tmessage: errorName,\n\t\t\t\tduration: 3000,\n\t\t\t\tposition: \"top-right\",\n\t\t\t});\n\t\t});\n\t}\n};\n"],"names":[],"mappings":";;;;;AAQa,MAAA,eAAe,CAAC,UAAwB;AACpD,MAAI,CAAC,MAAO;AAEZ,MAAI,iBAAiB,YAAY;AACzB,WAAA;AAAA,EACR;AACA,QAAM,WAAgB;AAAA,IACrB,eAAe;AAAA,IACf,gBAAgB;AAAA,IAChB,WAAW;AAAA,IACX,YAAY;AAAA,IACZ,aAAa;AAAA,IACb,WAAW;AAAA,IACX,UAAU;AAAA,IACV,gBAAgB;AAAA,IAChB,cAAc;AAAA,IACd,cAAc;AAAA,IACd,kBAAkB;AAAA,EAAA;AAEnB,MAAI,UAAU,UAAU;AACvB,gBAAY,UAAU,OAAO;AAAA,EAAA,OACvB;AACN,UAAM,YAAY,SAAS,MAAM,IAAI,KAAK;AAC1C,iBAAa,WAAW,KAAK;AAC7B,aAAS,MAAM;AACC,qBAAA;AAAA,QACd,OAAO;AAAA,QACP,SAAS;AAAA,QACT,UAAU;AAAA,QACV,UAAU;AAAA,MAAA,CACV;AAAA,IAAA,CACD;AAAA,EACF;AACD;"}